pepfile: "config/pep/project_config.yaml"
pepschema: "schemas/pep.yaml"

# basecaller model version(s), with their subsequent full model names to analyse
model:
  v4.3.0:
    - "dna_r10.4.1_e8.2_400bps_fast@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_hac@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_sup@v4.3.0"

# Parameters for quality control
QC:
  min_length: 1000 # remove reads shorter than this
  min_qscore: 10 # per read, minimum mean quality score
  depths: # randomly subsample reads to these depths
    - 100

# Nanopore sequencing mode - i.e., simplex, duplex
mode:
  - "simplex"
  - "duplex"

# parameters related to the truth set generation
truth:
  # Maximum indel length to allow in the truth and call variant sets
  max_indel: 50
  # The desired mash distance between the reference and donor when generating the truth set
  mash_distance: 0.005
  # The minimum mash distance between the reference and donor when generating the truth set
  min_mash_distance: 0.002
  # The maximum mash distance between the reference and donor when generating the truth set
  max_mash_distance: 0.015
  # The maximum number of assemblies to download for distance calculation
  max_assemblies: 10000

# number of times to repeat running the variant calling rules. This is intended for
# benchmarking purposes only, and should be set to 1 for normal use.
repeat: 1

callers:
  bcftools:
    threads: 4
    memory: 8000
    runtime: "2h"
    container: "docker://quay.io/biocontainers/bcftools:1.19--h8b25389_0"
    extension: "sh"
  clair3:
    threads: 4
    memory: 8000
    runtime: "1h"
    container: "docker://quay.io/mbhall88/clair3:1.0.5"
    extension: "sh"
  longshot:
    threads: 1
    memory: 2000
    runtime: "1h"
    conda: "../envs/longshot.yaml"
    extension: "sh"
  freebayes:
    threads: 1
    memory: 8000
    runtime: "2h"
    conda: "../envs/freebayes.yaml"
    extension: "sh"
  deepvariant:
    threads: 4
    memory: 8000
    runtime: "2h"
    container: "docker://google/deepvariant:1.6.0"
    extension: "sh"