pepfile: "config/pep/project_config.yaml"
pepschema: "schemas/pep.yaml"

# basecaller model version(s), with their subsequent full model names to analyse
model:
  v4.3.0:
    - "dna_r10.4.1_e8.2_400bps_fast@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_hac@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_sup@v4.3.0"

# Parameters for quality control
QC:
  min_length: 1000 # remove reads shorter than this
  min_qscore: 10 # per read, minimum mean quality score
  depths: # randomly subsample reads to these depths
    - 100

# Nanopore sequencing mode - i.e., simplex, duplex
mode:
  - "simplex"
  - "duplex"

# parameters related to the truth set generation
truth:
  # Maximum indel length to allow in the truth and call variant sets
  max_indel: 50
  # The desired ANI between the reference and donor when generating the truth set
  ANI: 99.50
  # The minimum ANI between the reference and donor when generating the truth set
  min_ANI: 98.40
  # The maximum ANI between the reference and donor when generating the truth set
  max_ANI: 99.80
  # The maximum number of assemblies to download for distance calculation
  max_assemblies: 10000
  # The maximum allowed (CheckM) contamination of the donor
  max_contamination: 10
  # The minimum allowed (CheckM) completeness of the donor
  min_completeness: 90
  # The minimum allowed (CheckM) completeness percentile of the donor
  min_completeness_percentile: 25

# number of times to repeat running the variant calling rules. This is intended for
# benchmarking purposes only, and should be set to 1 for normal use.
repeat: 1

callers:
  - bcftools
  - clair3
  - deepvariant
  - freebayes
  - longshot
  - nanocaller

# list of callers that do not call indels
no_indels:
  - longshot