pepfile: "config/pep/project_config.yaml"
pepschema: "schemas/pep.yaml"

# basecaller model version(s), with their subsequent full model names to analyse
model:
  v4.3.0:
    - "dna_r10.4.1_e8.2_400bps_fast@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_hac@v4.3.0"
    - "dna_r10.4.1_e8.2_400bps_sup@v4.3.0"

# Parameters for quality control
QC:
  min_length: 1000  # remove reads shorter than this
  min_qscore: 10    # per read, minimum mean quality score
  depths:           # randomly subsample reads to these depths
    - 100        

# Nanopore sequencing mode - i.e., simplex, duplex
mode:
  - "simplex"
  - "duplex"