pep_version: 2.1.0
sample_table: "samples.csv"

sample_modifiers:
  derive:
    attributes: [reads_dir, reference_path]
    sources:
      source1: "/data/scratch/projects/punim2009/data/reads/simplex/"
      source2: "/data/scratch/projects/punim2009/data/references/{sample_name}.fa"